plugins {
    id 'software.ralf.app.platform.lib'
}

appPlatformBuildSrc {
    enablePublishing true
    enableInstrumentedTests true
}

dependencies {
    commonMainApi project(':presenter:public')
    commonMainApi project(':renderer:public')

    commonMainImplementation project(':presenter-compose:public')

    // Use a lower version to not force a higher version on consumers.
    androidMainApi libs.androidx.activity
    androidMainApi libs.viewbinding.api
    androidMainApi libs.recyclerView
    androidMainImplementation libs.androidx.core

    androidDeviceTestImplementation project(':kotlin-inject:public')
    androidDeviceTestImplementation libs.androidx.test.espresso
}
