plugins {
    id 'software.ralf.app.platform.lib'
}

appPlatformBuildSrc {
    enablePublishing true
}

dependencies {
    commonMainApi project(':presenter:public')
    commonMainApi project(':scope:public')
    commonMainImplementation libs.metro.runtime

    commonTestImplementation project(':internal:testing')
}
