VERSION_NAME=0.2.0-SNAPSHOT
GROUP=software.ralf.app.platform

org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.caching=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true

kotlin.mpp.stability.nowarn=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.distribution.downloadFromMaven=true
kotlin.native.ignoreDisabledTargets=true
# https://youtrack.jetbrains.com/issue/KT-82395
kotlin.incremental.js=false
kotlin.incremental.js.klib=false

org.jetbrains.compose.experimental.uikit.enabled=true

# This property does not work when setting up publishing through the DSL as we do.
# SONATYPE_AUTOMATIC_RELEASE=true
SONATYPE_HOST=CENTRAL_PORTAL
# Keep this set to false by default, otherwise publishing to Maven local is extremely slow. There is a bug:
# https://github.com/gradle/gradle/issues/26256
RELEASE_SIGNING_ENABLED=false

POM_DESCRIPTION=The App Platform is a lightweight application framework for state and memory management suitable for Kotlin Multiplatform projects, in particular Android, iOS, JVM, native and Web.
POM_INCEPTION_YEAR=2025

POM_URL=https://github.com/vRallev/app-platform/
POM_SCM_URL=https://github.com/vRallev/app-platform/
POM_SCM_CONNECTION=scm:git:git://github.com/vRallev/app-platform.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/vRallev/app-platform.git

POM_LICENCE_NAME=Apache-2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=vRallev
POM_DEVELOPER_NAME=Ralf Wondratschek
POM_DEVELOPER_URL=https://github.com/vRallev

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
