

package software.ralf.app.platform.metro.compiler.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link software.ralf.app.platform.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  private void run(String fileName) {
    runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box/contributesrenderer")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrenderer {
    private void run(String fileName) {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box/contributesrenderer/" + fileName);
    }

    @Test
    public void testAllFilesPresentInContributesrenderer() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box/contributesrenderer"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("constructorParametersWithoutInject.kt")
    public void testConstructorParametersWithoutInject() {
      run("constructorParametersWithoutInject.kt");
    }

    @Test
    @TestMetadata("defaultConstructorRenderer.kt")
    public void testDefaultConstructorRenderer() {
      run("defaultConstructorRenderer.kt");
    }

    @Test
    @TestMetadata("explicitModelType.kt")
    public void testExplicitModelType() {
      run("explicitModelType.kt");
    }

    @Test
    @TestMetadata("inferredFromHierarchy.kt")
    public void testInferredFromHierarchy() {
      run("inferredFromHierarchy.kt");
    }

    @Test
    @TestMetadata("inferredFromHierarchyMultipleLevels.kt")
    public void testInferredFromHierarchyMultipleLevels() {
      run("inferredFromHierarchyMultipleLevels.kt");
    }

    @Test
    @TestMetadata("injectConstructorRenderer.kt")
    public void testInjectConstructorRenderer() {
      run("injectConstructorRenderer.kt");
    }

    @Test
    @TestMetadata("injectSecondaryConstructorSkipsProvider.kt")
    public void testInjectSecondaryConstructorSkipsProvider() {
      run("injectSecondaryConstructorSkipsProvider.kt");
    }

    @Test
    @TestMetadata("innerModel.kt")
    public void testInnerModel() {
      run("innerModel.kt");
    }

    @Test
    @TestMetadata("innerRenderer.kt")
    public void testInnerRenderer() {
      run("innerRenderer.kt");
    }

    @Test
    @TestMetadata("sealedHierarchy.kt")
    public void testSealedHierarchy() {
      run("sealedHierarchy.kt");
    }

    @Test
    @TestMetadata("sealedHierarchyDisabled.kt")
    public void testSealedHierarchyDisabled() {
      run("sealedHierarchyDisabled.kt");
    }

    @Test
    @TestMetadata("sealedHierarchyInDependencyModule.kt")
    public void testSealedHierarchyInDependencyModule() {
      run("sealedHierarchyInDependencyModule.kt");
    }
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box/contributesrobot")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrobot {
    private void run(String fileName) {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box/contributesrobot/" + fileName);
    }

    @Test
    public void testAllFilesPresentInContributesrobot() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box/contributesrobot"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("constructorParametersWithoutInject.kt")
    public void testConstructorParametersWithoutInject() {
      run("constructorParametersWithoutInject.kt");
    }

    @Test
    @TestMetadata("defaultConstructorRobot.kt")
    public void testDefaultConstructorRobot() {
      run("defaultConstructorRobot.kt");
    }

    @Test
    @TestMetadata("indirectSupertype.kt")
    public void testIndirectSupertype() {
      run("indirectSupertype.kt");
    }

    @Test
    @TestMetadata("injectClassSkipsProvider.kt")
    public void testInjectClassSkipsProvider() {
      run("injectClassSkipsProvider.kt");
    }

    @Test
    @TestMetadata("injectConstructorRobot.kt")
    public void testInjectConstructorRobot() {
      run("injectConstructorRobot.kt");
    }

    @Test
    @TestMetadata("injectSecondaryConstructorSkipsProvider.kt")
    public void testInjectSecondaryConstructorSkipsProvider() {
      run("injectSecondaryConstructorSkipsProvider.kt");
    }
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box/contributesscoped")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesscoped {
    private void run(String fileName) {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box/contributesscoped/" + fileName);
    }

    @Test
    public void testAllFilesPresentInContributesscoped() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/box/contributesscoped"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("constructorParametersWithoutInject.kt")
    public void testConstructorParametersWithoutInject() {
      run("constructorParametersWithoutInject.kt");
    }

    @Test
    @TestMetadata("defaultScoped.kt")
    public void testDefaultScoped() {
      run("defaultScoped.kt");
    }

    @Test
    @TestMetadata("injectSecondaryConstructorSkipsProvider.kt")
    public void testInjectSecondaryConstructorSkipsProvider() {
      run("injectSecondaryConstructorSkipsProvider.kt");
    }

    @Test
    @TestMetadata("innerClass.kt")
    public void testInnerClass() {
      run("innerClass.kt");
    }

    @Test
    @TestMetadata("onlyScoped.kt")
    public void testOnlyScoped() {
      run("onlyScoped.kt");
    }

    @Test
    @TestMetadata("transitiveScoped.kt")
    public void testTransitiveScoped() {
      run("transitiveScoped.kt");
    }
  }
}
