

package software.ralf.app.platform.metro.compiler.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link software.ralf.app.platform.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump")
@TestDataPath("$PROJECT_ROOT")
public class FirDumpTestGenerated extends AbstractFirDumpTest {
  private void run(String fileName) {
    runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDump() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesrenderer")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrenderer {
    private void run(String fileName) {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesrenderer/" + fileName);
    }

    @Test
    public void testAllFilesPresentInContributesrenderer() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesrenderer"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("constructorParametersWithoutInject.kt")
    public void testConstructorParametersWithoutInject() {
      run("constructorParametersWithoutInject.kt");
    }

    @Test
    @TestMetadata("defaultConstructorRenderer.kt")
    public void testDefaultConstructorRenderer() {
      run("defaultConstructorRenderer.kt");
    }

    @Test
    @TestMetadata("defaultConstructorRendererIr.kt")
    public void testDefaultConstructorRendererIr() {
      run("defaultConstructorRendererIr.kt");
    }
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesrobot")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrobot {
    private void run(String fileName) {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesrobot/" + fileName);
    }

    @Test
    public void testAllFilesPresentInContributesrobot() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesrobot"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("constructorParametersWithoutInject.kt")
    public void testConstructorParametersWithoutInject() {
      run("constructorParametersWithoutInject.kt");
    }

    @Test
    @TestMetadata("defaultConstructorRobot.kt")
    public void testDefaultConstructorRobot() {
      run("defaultConstructorRobot.kt");
    }

    @Test
    @TestMetadata("defaultConstructorRobotIr.kt")
    public void testDefaultConstructorRobotIr() {
      run("defaultConstructorRobotIr.kt");
    }
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesscoped")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesscoped {
    private void run(String fileName) {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesscoped/" + fileName);
    }

    @Test
    public void testAllFilesPresentInContributesscoped() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesscoped"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("constructorParametersWithoutInject.kt")
    public void testConstructorParametersWithoutInject() {
      run("constructorParametersWithoutInject.kt");
    }

    @Test
    @TestMetadata("defaultScoped.kt")
    public void testDefaultScoped() {
      run("defaultScoped.kt");
    }
  }
}
