

package software.ralf.app.platform.metro.compiler.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link software.ralf.app.platform.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class FirDiagnosticTestGenerated extends AbstractFirDiagnosticTest {
  private void run(String fileName) {
    runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrenderer")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrenderer {
    private void run(String fileName) {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrenderer/" + fileName);
    }

    @Test
    public void testAllFilesPresentInContributesrenderer() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrenderer"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("modelTypeMustBeExplicitWhenNotInferable.kt")
    public void testModelTypeMustBeExplicitWhenNotInferable() {
      run("modelTypeMustBeExplicitWhenNotInferable.kt");
    }

    @Test
    @TestMetadata("multipleConstructorsMustUseInject.kt")
    public void testMultipleConstructorsMustUseInject() {
      run("multipleConstructorsMustUseInject.kt");
    }

    @Test
    @TestMetadata("redundantInjectOnZeroArgConstructor.kt")
    public void testRedundantInjectOnZeroArgConstructor() {
      run("redundantInjectOnZeroArgConstructor.kt");
    }

    @Test
    @TestMetadata("rendererMustNotBeSingleton.kt")
    public void testRendererMustNotBeSingleton() {
      run("rendererMustNotBeSingleton.kt");
    }
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrobot")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrobot {
    private void run(String fileName) {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrobot/" + fileName);
    }

    @Test
    public void testAllFilesPresentInContributesrobot() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrobot"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("classMustImplementRobot.kt")
    public void testClassMustImplementRobot() {
      run("classMustImplementRobot.kt");
    }

    @Test
    @TestMetadata("multipleConstructorsMustUseInject.kt")
    public void testMultipleConstructorsMustUseInject() {
      run("multipleConstructorsMustUseInject.kt");
    }

    @Test
    @TestMetadata("onlyAppScopeSupported.kt")
    public void testOnlyAppScopeSupported() {
      run("onlyAppScopeSupported.kt");
    }

    @Test
    @TestMetadata("robotMustNotBeSingleton.kt")
    public void testRobotMustNotBeSingleton() {
      run("robotMustNotBeSingleton.kt");
    }
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesscoped")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesscoped {
    private void run(String fileName) {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesscoped/" + fileName);
    }

    @Test
    public void testAllFilesPresentInContributesscoped() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesscoped"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("multipleConstructorsMustUseInject.kt")
    public void testMultipleConstructorsMustUseInject() {
      run("multipleConstructorsMustUseInject.kt");
    }

    @Test
    @TestMetadata("multipleOtherSupertypes.kt")
    public void testMultipleOtherSupertypes() {
      run("multipleOtherSupertypes.kt");
    }

    @Test
    @TestMetadata("mustImplementScoped.kt")
    public void testMustImplementScoped() {
      run("mustImplementScoped.kt");
    }

    @Test
    @TestMetadata("noSupertypes.kt")
    public void testNoSupertypes() {
      run("noSupertypes.kt");
    }

    @Test
    @TestMetadata("useContributesScopedInsteadOfContributesBinding.kt")
    public void testUseContributesScopedInsteadOfContributesBinding() {
      run("useContributesScopedInsteadOfContributesBinding.kt");
    }
  }
}
