plugins {
    id 'software.ralf.app.platform.lib'
}

appPlatformBuildSrc {
    enableCompose true
    enablePublishing true
}

dependencies {
    commonMainApi project(':robot:public')
    commonMainApi project(':scope:public')
    commonMainApi compose.uiTest

    commonMainImplementation project(':robot-internal:public')

    commonTestImplementation project(':metro:public')
    commonTestImplementation project(':scope:testing')
    commonTestImplementation libs.metro.runtime

    desktopTestImplementation compose.material
    iosTestImplementation compose.material
}
