plugins {
    id 'software.ralf.app.platform.lib'
}

appPlatformBuildSrc {
    enableMolecule true
    enablePublishing true
}

dependencies {
    commonMainApi project(':presenter:public')
    commonTestImplementation project(':internal:testing')
    commonTestImplementation project(':presenter-molecule:testing')
}
