plugins {
    id 'software.ralf.app.platform'

    // This plugin lives in the buildSrc directory and is not published.
    // It's used to manage certain configurations and dependencies for all
    // :sample:* modules, otherwise we'd need to repeat them several times.
    id 'software.ralf.app.platform.lib'
}

appPlatform {
    enableComposeUi true
    enableMetro true
    enableModuleStructure true
    enableMoleculePresenters true
}

appPlatformBuildSrc {
    enableAndroidResources true
}

dependencies {
    commonMainApi project(':sample:templates:public')

    commonMainImplementation compose.components.resources
    commonMainImplementation compose.material

    commonTestImplementation project(':sample:user:testing')
}
