package software.ralf.app.platform.metro.compiler

import dev.zacsweers.metro.compiler.compat.CompatContext
import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI

/** Generates App Platform declarations in IR or completes bodies generated by the FIR fallback. */
@OptIn(UnsafeDuringIrConstructionAPI::class)
internal class AppPlatformIrGenerationExtension(
  private val generateDeclarationsInIr: Boolean,
) : IrGenerationExtension {
  override fun generate(moduleFragment: IrModuleFragment, pluginContext: IrPluginContext) {
    AppPlatformIrContributionGenerator(
        pluginContext = pluginContext,
        compatContext = CompatContext.create(),
        generateDeclarationsInIr = generateDeclarationsInIr,
      )
      .generate(moduleFragment)
  }
}
