pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()

        maven {
            url = "https://central.sonatype.com/repository/maven-snapshots/"
        }
    }

    versionCatalogs {
        libs {
            from files('../gradle/libs.versions.toml')
        }
    }
}

rootProject.name = 'gradle-plugin'

include 'module-structure'
include 'plugin'
