plugins {
    id 'software.ralf.app.platform.lib'
}

appPlatformBuildSrc {
    enableKotlinInject true
    enableMetro true
    enableMolecule true
    enablePublishing true

    // Had to be disabled because KSP2 is disabled, which produces warnings for the Kotlin compilation.
    kotlinWarningsAsErrors false
}

dependencies {
    commonMainApi project(':scope:public')

    commonTestImplementation project(':kotlin-inject:impl')
    commonTestImplementation libs.kotlin.inject.runtime.kmp
}
