plugins {
    id 'software.ralf.app.platform.lib.jvm'
}

appPlatformBuildSrc {
    enablePublishing true
}

dependencies {
    api libs.ksp.api

    api libs.kotlin.poet
    api libs.kotlin.poet.ksp

    // Gives us access to annotations.
    api project(':di-common:public')
    api project(':scope:public')
}

// Skip ABI validation for compiler tooling.
tasks.named('checkKotlinAbi').configure {
    it.enabled = false
}
tasks.named('updateKotlinAbi').configure {
    it.enabled = false
}
