plugins {
    id 'software.ralf.app.platform.lib'
}

appPlatformBuildSrc {
    enableCompose true
    enableInstrumentedTests true
    enablePublishing true
}

dependencies {
    commonMainApi project(':presenter:public')
    commonMainApi project(':presenter-molecule:public')
    commonMainApi project(':renderer:public')
    commonMainApi project(':scope:public')
    commonMainApi libs.compose.foundation

    commonMainImplementation libs.navigation.event.compose

    androidMainApi project(':renderer-android-view:public')

    commonTestImplementation project(':metro:public')
    commonTestImplementation project(':scope:testing')
    commonTestImplementation libs.metro.runtime

    androidTestImplementation project(':metro:public')
    androidTestImplementation project(':presenter-molecule:impl')
    androidTestImplementation libs.androidx.activity.compose
    androidTestImplementation libs.androidx.test.espresso
    androidTestImplementation libs.compose.ui.test.junit4
    androidTestImplementation libs.compose.ui.test.junit4.android
    androidTestImplementation libs.compose.ui.test.manifest
    androidTestImplementation libs.metro.runtime
}
