plugins {
    id 'software.ralf.app.platform.lib'
}

appPlatformBuildSrc {
    enableCompose true
    enableInstrumentedTests true
    enableAndroidResources true
    enablePublishing true
}

dependencies {
    commonMainApi project(':presenter:public')
    commonMainApi project(':presenter-compose:public')
    commonMainApi project(':renderer:public')
    commonMainApi project(':scope:public')
    commonMainApi libs.compose.foundation

    commonMainImplementation libs.navigation.event.compose

    androidMainApi project(':renderer-android-view:public')

    commonTestImplementation project(':metro:public')
    commonTestImplementation project(':scope:testing')
    commonTestImplementation libs.metro.runtime

    androidDeviceTestImplementation project(':metro:public')
    androidDeviceTestImplementation project(':presenter-compose:impl')
    androidDeviceTestImplementation libs.androidx.activity.compose
    androidDeviceTestImplementation libs.androidx.test.espresso
    androidDeviceTestImplementation libs.compose.ui.test.junit4
    androidDeviceTestImplementation libs.compose.ui.test.junit4.android
    androidDeviceTestImplementation libs.compose.ui.test.manifest
    androidDeviceTestImplementation libs.metro.runtime
}
