includeBuild('../gradle-plugin') {
    dependencySubstitution {
        substitute module("$GROUP:gradle-plugin") using project(':plugin')
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()

        maven {
            url = "https://central.sonatype.com/repository/maven-snapshots/"
        }
    }

    versionCatalogs {
        libs {
            from files('../gradle/libs.versions.toml')
        }
    }
}
