grid-rows: 4
grid-columns: 1
vertical-gap: 0

e2e: "E2E\nTests" {
  width: 640
  height: 140
  style: {
    fill: "#D9EAD3"
    stroke: "#6AA84F"
    stroke-width: 2
    font: mono
    font-color: "#333333"
    font-size: 22
    bold: false
  }
}
integration: "Integration Tests" {
  width: 640
  height: 140
  style: {
    fill: "#FCE5CD"
    stroke: "#E69138"
    stroke-width: 2
    font: mono
    font-color: "#333333"
    font-size: 18
    bold: false
  }
}
instrumented: "Instrumented Tests" {
  width: 640
  height: 140
  style: {
    fill: "#D9E7F7"
    stroke: "#6D9EEB"
    stroke-width: 2
    font: mono
    font-color: "#333333"
    font-size: 22
    bold: false
  }
}
unit: "Unit Tests" {
  width: 640
  height: 140
  style: {
    fill: "#F3F3F3"
    stroke: "#777777"
    stroke-width: 2
    font: mono
    font-color: "#333333"
    font-size: 22
    bold: false
  }
}
