GROUP=software.ralf.app.platform.template

org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# https://youtrack.jetbrains.com/issue/KT-82395
kotlin.incremental.js=false
kotlin.incremental.js.klib=false
